# Generated by Django 4.2.30 on 2026-05-12 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIquery',
            fields=[
                ('query_id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ClassOffering',
            fields=[
                ('offer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_id', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('instructor', models.IntegerField()),
                ('day1', models.CharField(max_length=3)),
                ('day2', models.CharField(max_length=3)),
                ('time1', models.TimeField()),
                ('time2', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField()),
                ('target', models.IntegerField()),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=20)),
                ('avg_rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(default=-1.0)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_college0.classoffering')),
            ],
        ),
        migrations.CreateModel(
            name='Grad_Apply',
            fields=[
                ('app_id', models.IntegerField(primary_key=True, serialize=False)),
                ('app_status', models.CharField(default='pending', max_length=8)),
                ('applicant', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('i_id', models.IntegerField(primary_key=True, serialize=False)),
                ('i_name', models.CharField(max_length=25)),
                ('warnings', models.IntegerField(default=0)),
                ('department', models.CharField(max_length=20)),
                ('i_email', models.EmailField(max_length=254)),
                ('current_rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor_Apply',
            fields=[
                ('app_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('app_status', models.CharField(default='pending', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('p_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=20)),
                ('quota', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=25)),
                ('total_gpa', models.FloatField()),
                ('semester_gpa', models.FloatField()),
                ('warnings', models.IntegerField(default=0)),
                ('program', models.CharField(max_length=20)),
                ('s_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Apply',
            fields=[
                ('app_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('app_status', models.CharField(default='pending', max_length=8)),
                ('gpa', models.FloatField()),
                ('prog', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Waitlist_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.IntegerField()),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_college0.classoffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_college0.student')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Course_Hist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failures', models.IntegerField(default=0)),
                ('passed', models.IntegerField(default=0)),
                ('course_taken', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_college0.course')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_college0.student')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('review_text', models.CharField(max_length=200)),
                ('taboo_words', models.IntegerField()),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='app_college0.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='Prog_Req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_college0.program')),
                ('requirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_college0.course')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_college0.student'),
        ),
        migrations.CreateModel(
            name='Major_Req_List',
            fields=[
            ],
            options={
                'verbose_name': 'Major',
                'verbose_name_plural': 'Majors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_college0.prog_req',),
        ),
    ]
